baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "username.github.io" # the base hostname & protocol for your site.

# header text
title: Get Cryptolocker
header: Help your business get Cryptolocker today

# for welcome page
# to replace image go to index.html
email:
  address: "technion@lolware.net"
  text: "technion @ lolware.net"

# disqus comment
disqus:
    shortname: "test" #your disqus comment short name

# google analytics
google:
    tracking-id: "" #your tracking id here

gems:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"

permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
